name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/apps/qrcodegen.fahrigunadi.dev
          git fetch --all
          git reset --hard origin/main
          npm install && npm run build
          go build
          sudo /usr/bin/supervisorctl restart qrcodegen.fahrigunadi.dev